PROCESS BEFORE OUTPUT.

  MODULE status_9000.

PROCESS AFTER INPUT.

  MODULE exit_command_9000 AT EXIT-COMMAND.

  MODULE user_command_9000.

PROCESS ON VALUE-REQUEST.
  FIELD: p_ruta  MODULE f4_ruta.
