PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTTEXTOS_SERV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTTEXTOS_SERV-POS .
    FIELD ZTTEXTOS_SERV-TIPO .
    FIELD ZTTEXTOS_SERV-TEXTO1 .
    FIELD ZTTEXTOS_SERV-TEXTO2 .
    FIELD ZTTEXTOS_SERV-TEXTO3 .
    FIELD ZTTEXTOS_SERV-TEXTO4 .
    FIELD ZTTEXTOS_SERV-TEXTO5 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTTEXTOS_SERV-POS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
