PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTTEMPARIO_SERV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTTEMPARIO_SERV-MODELO .
    FIELD ZTTEMPARIO_SERV-MODALIDAD .
    FIELD ZTTEMPARIO_SERV-LUGAR .
    FIELD ZTTEMPARIO_SERV-CAJA .
    FIELD ZTTEMPARIO_SERV-DIFERENCIAL .
    FIELD ZTTEMPARIO_SERV-TEMPARIO .
    FIELD ZTTEMPARIO_SERV-INTERVALO .
    FIELD ZTTEMPARIO_SERV-CANTIDAD .
    FIELD ZTTEMPARIO_SERV-TEMPARIO_TXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTTEMPARIO_SERV-MODELO .
    FIELD ZTTEMPARIO_SERV-MODALIDAD .
    FIELD ZTTEMPARIO_SERV-LUGAR .
    FIELD ZTTEMPARIO_SERV-CAJA .
    FIELD ZTTEMPARIO_SERV-DIFERENCIAL .
    FIELD ZTTEMPARIO_SERV-TEMPARIO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
