PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTPAUTA_SERV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTPAUTA_SERV-EQUIPO .
    FIELD ZTPAUTA_SERV-MARCA .
    FIELD ZTPAUTA_SERV-MODELO .
    FIELD ZTPAUTA_SERV-MODALIDAD .
    FIELD ZTPAUTA_SERV-LUGAR .
    FIELD ZTPAUTA_SERV-CAJA .
    FIELD ZTPAUTA_SERV-DIFERENCIAL .
    FIELD ZTPAUTA_SERV-MATERIAL .
    FIELD ZTPAUTA_SERV-MATNR .
    FIELD ZTPAUTA_SERV-DESCRIPCION_MAT .
    FIELD ZTPAUTA_SERV-INTERVALO .
    FIELD ZTPAUTA_SERV-CANTIDAD .
    FIELD ZTPAUTA_SERV-SUCURSAL .
    FIELD ZTPAUTA_SERV-USO .
    FIELD ZTPAUTA_SERV-USO_INICIAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTPAUTA_SERV-EQUIPO .
    FIELD ZTPAUTA_SERV-MARCA .
    FIELD ZTPAUTA_SERV-MODELO .
    FIELD ZTPAUTA_SERV-MODALIDAD .
    FIELD ZTPAUTA_SERV-LUGAR .
    FIELD ZTPAUTA_SERV-CAJA .
    FIELD ZTPAUTA_SERV-DIFERENCIAL .
    FIELD ZTPAUTA_SERV-MATERIAL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
