PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTMOBRA_SERV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTMOBRA_SERV-SUCURSAL .
    FIELD ZTMOBRA_SERV-EQUIPO .
    FIELD ZTMOBRA_SERV-IMPORTE_TALLER .
    FIELD ZTMOBRA_SERV-IMPORTE_TERRENO .
    FIELD ZTMOBRA_SERV-IMPORTE_CAMIONL .
    FIELD ZTMOBRA_SERV-DESAYUNO .
    FIELD ZTMOBRA_SERV-ALMUERZO .
    FIELD ZTMOBRA_SERV-CENA_COMIDA .
    FIELD ZTMOBRA_SERV-ALOJAMIENTO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTMOBRA_SERV-SUCURSAL .
    FIELD ZTMOBRA_SERV-EQUIPO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
