PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTDTO_SERV_MANT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTDTO_SERV_MANT-TIPO_DTO .
    FIELD ZTDTO_SERV_MANT-K1000 .
    FIELD ZTDTO_SERV_MANT-K2000 .
    FIELD ZTDTO_SERV_MANT-K4000 .
    FIELD ZTDTO_SERV_MANT-K6000 .
    FIELD ZTDTO_SERV_MANT-EQUIPO .
    FIELD ZTDTO_SERV_MANT-DESCRIPCION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTDTO_SERV_MANT-TIPO_DTO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
