PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTVALOR_CONTRATO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTVALOR_CONTRATO-VALOR1 .
    FIELD ZTVALOR_CONTRATO-VALOR2 .
    FIELD ZTVALOR_CONTRATO-VALOR3 .
    FIELD ZTVALOR_CONTRATO-VALOR4 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTVALOR_CONTRATO-VALOR1 .
    FIELD ZTVALOR_CONTRATO-VALOR2 .
    FIELD ZTVALOR_CONTRATO-VALOR3 .
    FIELD ZTVALOR_CONTRATO-VALOR4 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
