PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTEXTOS_FIJOS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTEXTOS_FIJOS-POS .
    FIELD ZTEXTOS_FIJOS-TIPO .
    FIELD ZTEXTOS_FIJOS-TEXTO1 .
    FIELD ZTEXTOS_FIJOS-TEXTO2 .
    FIELD ZTEXTOS_FIJOS-TEXTO3 .
    FIELD ZTEXTOS_FIJOS-TEXTO4 .
    FIELD ZTEXTOS_FIJOS-TEXTO5 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTEXTOS_FIJOS-POS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
