PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTPAUTA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTPAUTA-EQUIPO .
    FIELD ZTPAUTA-MARCA .
    FIELD ZTPAUTA-MODELO .
    FIELD ZTPAUTA-MODALIDAD .
    FIELD ZTPAUTA-LUGAR .
    FIELD ZTPAUTA-CAJA .
    FIELD ZTPAUTA-DIFERENCIAL .
    FIELD ZTPAUTA-MATERIAL .
    FIELD ZTPAUTA-MATNR .
    FIELD ZTPAUTA-DESCRIPCION_MAT .
    FIELD ZTPAUTA-INTERVALO_MINE .
    FIELD ZTPAUTA-CANTIDAD .
    FIELD ZTPAUTA-SUCURSAL .
    FIELD ZTPAUTA-USO .
    FIELD ZTPAUTA-USO_INICIAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTPAUTA-EQUIPO .
    FIELD ZTPAUTA-MARCA .
    FIELD ZTPAUTA-MODELO .
    FIELD ZTPAUTA-MODALIDAD .
    FIELD ZTPAUTA-LUGAR .
    FIELD ZTPAUTA-CAJA .
    FIELD ZTPAUTA-DIFERENCIAL .
    FIELD ZTPAUTA-MATERIAL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
