PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTPARAM_COTI CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTPARAM_COTI-TIPO .
    FIELD ZTPARAM_COTI-NUMERO .
    FIELD ZTPARAM_COTI-VALOR1 .
    FIELD ZTPARAM_COTI-VALOR2 .
    FIELD ZTPARAM_COTI-VALOR3 .
    FIELD ZTPARAM_COTI-VALOR4 .
    FIELD ZTPARAM_COTI-OPCION .
    FIELD ZTPARAM_COTI-DESCRIPCION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTPARAM_COTI-TIPO .
    FIELD ZTPARAM_COTI-NUMERO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
